apps/users/urls.py
from django.urls import path
from .views import (user_logout,user_login,forgot_password_view,profile_organizations_view, 
                    SkillRetrieveUpdateDestroyView, VolunteerRetrieveUpdateDestroyView, 
                    BadgeListCreateView, SkillListCreateView, VolunteerListCreateView, 
                    OrganizationListCreateView,VolunteerDetailView, AddSkillToVolunteerView,
    RemoveSkillFromVolunteerView, my_organizations_view ,OrganizationDetailView,
    OrganizationRetrieveUpdateDestroyView, organization_memberships_view,user_signup, update_profile_picture,
    update_background_image,update_profile_logo,update_obackground_image,AddInterestToVolunteerView, 
    RemoveInterestFromVolunteerView, AddInterestToOrganizationView, RemoveInterestFromOrganizationView,
    VolunteerMatchView,VolunteerRelationships,unfollow_volunteer,follow_volunteer,follow_organization,unfollow_organization,
    skills_admin_view, AddSkillView, AddInterestView, interest_admin_view,AddOrganizationMembershipView,accept_membership_view,
    SuggestedVolunteerList, like_post, is_liked, VolunteerDetailView2,
)
app_name = 'users'

urlpatterns = [
    #Users
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='user_logout'),
    path('badges/', BadgeListCreateView.as_view(), name='badge-list-create'),
    path('forgot-password/', forgot_password_view, name='forgot-password'),
    path('sign-up/', user_signup, name='sign-up'),

    path('skills/', SkillListCreateView.as_view(), name='skill-list-create'),
    path('api/skills/<int:id>/', SkillRetrieveUpdateDestroyView.as_view(), name='skills-detail'),

    #Volunteers
    path('volunteers/', VolunteerListCreateView.as_view(), name='volunteer-list-create'),
    path('profile-volunteer/', VolunteerDetailView.as_view(), name='profile-volunteer'),
    path('volunteer/<int:pk>/', VolunteerDetailView.as_view(), name='volunteer-detail'),  
    path('api/volunteer/<int:id>/add_skill/', AddSkillToVolunteerView.as_view(), name='add-skill-to-volunteer'),
    path('api/volunteer/<int:id>/remove_skill/', RemoveSkillFromVolunteerView.as_view(), name='remove-skill-from-volunteer'),
    path('api/volunteer/<int:id>/update_profile_picture/', update_profile_picture, name='update-profile-picture'),
    path('api/volunteer/<int:id>/update_background_image/', update_background_image, name='update-background-image'),
    path('api/volunteer/<int:id>/add_interest/', AddInterestToVolunteerView.as_view(), name='add-intereest-to-volunteer'),
    path('api/volunteer/<int:id>/remove_interest/', RemoveInterestFromVolunteerView.as_view(), name='remove-interest-from-volunteer'),
    path("relationships/", VolunteerRelationships, name="relationships"),
    path('unfollow_volunteer/<int:volunteer_id>/', unfollow_volunteer, name='unfollow-volunteer'),
    path('follow_volunteer/<int:volunteer_id>/', follow_volunteer, name='follow-volunteer'),
    path('api/suggestions/', SuggestedVolunteerList.as_view(), name='suggested_volunteers'),
    path('like_post/<int:post_id>/', like_post, name='like_post'),
    path('is_liked/<int:post_id>/', is_liked, name='is_liked'),

    #Organizations
    path('my-organizations/', my_organizations_view, name='my-organizations'),
    path('organizations/', OrganizationListCreateView.as_view(), name='organizations-list-create'),
    path('organizations/<int:pk>/', OrganizationDetailView.as_view(), name='organization-detail'),
    path('api/organization/<int:id>/', OrganizationRetrieveUpdateDestroyView.as_view(), name='update-organization'),
    path('api/organization/<int:id>/update_profile_logo/', update_profile_logo, name='update-profile-logo'),
    path('api/organization/<int:id>/update_background_image/', update_obackground_image, name='update-obackground-image'),
    path('api/organization/<int:id>/add_interest/', AddInterestToOrganizationView.as_view(), name='add-intereest-to-organization'),
    path('api/organization/<int:id>/remove_interest/', RemoveInterestFromOrganizationView.as_view(), name='remove-interest-from-organization'),
    path('organization-match/', VolunteerMatchView.as_view(), name='organization-match'),
    path('organization-match/subscribe/<int:organization_id>/', VolunteerMatchView.as_view(), name='organization-subscribe'),

    path('unfollow_organization/<int:organization_id>/', unfollow_organization, name='unfollow-organization'),
    path('organization/<int:organization_id>/follow', follow_organization, name='follow-organization'),
    


    path('profile-organization/<int:pk>/', OrganizationDetailView.as_view(), name='profile-organization'),
    path('organization-memberships/', organization_memberships_view, name='organization-memberships'),
     path('accept-membership/<int:membership_id>/', accept_membership_view, name='accept-membership'),

    #Administration
    path('skills-admin/', skills_admin_view, name='skills-admin'),
    path('add-skill/', AddSkillView.as_view(), name='add-skill'),

    path('interest-admin/', interest_admin_view, name='interest-admin'),
    path('add-interest/', AddInterestView.as_view(), name='add-interest'),


]

post/urls.py
from django.urls import path
from post.views import PostListCreate, CommentListCreate

urlpatterns = [
    path('postlist/', PostListCreate.as_view(), name='api_posts_list_create'),
    path('comment/', CommentListCreate.as_view(), name='api_comments_list_create'),

]

users/urls.py
from django.urls import path

from users.views import (
    user_login,
    user_logout,
    user_signup,
    forgot_password_view,
    profile,
    followers,
    following,
    follow, organization_memberships_view, follow1, BadgeListCreateView, SkillListCreateView,
    SkillRetrieveUpdateDestroyView, VolunteerListCreateView, VolunteerDetailView, VolunteerRetrieveUpdateDestroyView,
    AddSkillToVolunteerView, RemoveSkillFromVolunteerView, my_organizations_view, OrganizationListCreateView,
    OrganizationDetailView, OrganizationRetrieveUpdateDestroyView,
)

app_name = 'users'

urlpatterns = [
    # Users
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='user_logout'),
    path('badges/', BadgeListCreateView.as_view(), name='badge-list-create'),
    path('forgot-password/', forgot_password_view, name='forgot-password'),
    path('sign-up/', user_signup, name='sign-up'),
    path("profile/<int:user_id>/", profile, name="profile"),
    path("followers/<int:user_id>/", followers, name="followers"),
    path("following/<int:user_id>/", following, name="following"),
    path("follow/<int:user_id>", follow, name="follow"),
    path("follow1/<int:user_id>", follow1, name="follow1"),
    path('skills/', SkillListCreateView.as_view(), name='skill-list-create'),
    path('api/skills/<int:id>/', SkillRetrieveUpdateDestroyView.as_view(), name='skills-detail'),

    # Volunteers
    path('volunteers/', VolunteerListCreateView.as_view(), name='volunteer-list-create'),
    path('profile-volunteer/', VolunteerDetailView.as_view(), name='profile-volunteer'),
    path('volunteer/<int:pk>/', VolunteerDetailView.as_view(), name='volunteer-detail'),
    path('api/volunteer/<int:id>/', VolunteerRetrieveUpdateDestroyView.as_view(),
         name='volunteer-detail-update-delete'),
    path('api/volunteer/<int:id>/add_skill/', AddSkillToVolunteerView.as_view(), name='add-skill-to-volunteer'),
    path('api/volunteer/<int:id>/remove_skill/', RemoveSkillFromVolunteerView.as_view(),
         name='remove-skill-from-volunteer'),

    # Organizations
    path('my-organizations/', my_organizations_view, name='my-organizations'),
    path('organizations/', OrganizationListCreateView.as_view(), name='organizations-list-create'),
    path('organizations/<int:pk>/', OrganizationDetailView.as_view(), name='organization-detail'),
    path('api/organization/<int:id>/', OrganizationRetrieveUpdateDestroyView.as_view(), name='update-organization'),
    path('profile-organization/<int:org_id>/', OrganizationDetailView.as_view(), name='organization-detail'),
    path('organization-memberships/', organization_memberships_view, name='organization-memberships'),

]

volunteer_platform/urls.py
"""
URL configuration for volunteer_platform project.

"""
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', include('apps.home.urls')),
    path('admin/', admin.site.urls),
    path('', include(('apps.users.urls', 'users'), namespace='users')),
    path('post/', include('apps.post.urls')),
   # path('event/', include('apps.event.urls')),
    path('event/', include(('apps.event.urls', 'event'), namespace='event')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    profile_image = models.ImageField("profile_image", upload_to="users_profile/", blank=True)
    background_image = models.ImageField("background_image", upload_to="users_profile/", blank=True, null=True)
    headline = models.TextField(max_length=80, blank=True)
    # like_posts = models.ManyToManyField(
    #     "posts.Post",
    #     verbose_name="Like posts list",
    #     related_name="like_users",
    #     blank=True,
    # )
    following = models.ManyToManyField(
        "self",
        verbose_name="following users",
        related_name="followers",
        symmetrical=False,
        through="users.Relationship",
    )

    def __str__(self):
        return self.username


class Relationship(models.Model):
    from_user = models.ForeignKey(
        User,
        verbose_name="followers",
        related_name="following_relationships",
        on_delete=models.CASCADE,
    )
    to_user = models.ForeignKey(
        User,
        verbose_name="following",
        related_name="follower_relationships",
        on_delete=models.CASCADE,
    )
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"({self.from_user} -> {self.to_user})"


class Badge(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    image = models.ImageField(upload_to='badge_images/')

    def __str__(self):
        return self.name


class Skill(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.name


class Volunteer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # profile_picture = models.ImageField(upload_to='volunteer_profile/', blank=True, null=True)
    # background_image = models.ImageField(upload_to='volunteer_profile/', blank=True, null=True)
    bio = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20)
    experiences = models.TextField()
    interests = models.TextField()
    badges = models.ManyToManyField(Badge, related_name='volunteers', blank=True)
    skills = models.ManyToManyField(Skill, related_name='volunteers', blank=True)
    location = models.CharField(max_length=255, blank=True,
                                null=True)  # Consider using a more detailed location model or a library like django-cities for more granularity
    date_of_birth = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"


class Organization(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=20)
    website = models.URLField(blank=True)
    logo = models.ImageField(upload_to='organization_profile/', blank=True)
    background_image = models.ImageField(upload_to='organization_profile/', blank=True, null=True)
    volunteers = models.ManyToManyField(Volunteer, through='OrganizationMembership', related_name='organizations')

    def __str__(self):
        return self.name


class OrganizationMembership(models.Model):
    ROLES = (
        ('owner', 'Owner'),
        ('admin', 'Admin'),
        ('member', 'Member'),
    )

    volunteer = models.ForeignKey(Volunteer, on_delete=models.CASCADE, null=True)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    role = models.CharField(max_length=20, choices=ROLES)
    date_joined = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            # Asegurando que un Volunteer solo tenga un tipo de rol específico en una organización
            models.UniqueConstraint(
                fields=['volunteer', 'organization', 'role'],
                name='unique_membership'
            )
        ]


# class Follower(models.Model):
#     follower_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="followings")
#     volunteer = models.ForeignKey(Volunteer, on_delete=models.CASCADE, blank=True, null=True, related_name="followers")
#     organization = models.ForeignKey(Organization, on_delete=models.CASCADE, blank=True, null=True,
#                                      related_name="followers")
#     date_followed = models.DateTimeField(auto_now_add=True)
#
#     class Meta:
#         constraints = [
#             models.CheckConstraint(
#                 check=(
#                         models.Q(volunteer__isnull=False, organization__isnull=True) |
#                         models.Q(volunteer__isnull=True, organization__isnull=False)
#                 ),
#                 name='only_one_follow_target'
#             ),
#             models.UniqueConstraint(
#                 fields=['follower_user', 'volunteer', 'organization'],
#                 name='unique_follow'
#             )
#         ]

apps/users/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Volunteer

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class SignupForm(forms.Form):
    username = forms.CharField()
    first_name = forms.CharField()  # Corregido de 'firt_name' a 'first_name'
    last_name = forms.CharField()
    
    email = forms.EmailField()

    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput, label='Confirm Password')

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("Passwords do not match. Please enter the same password in both fields.")
        
        return cleaned_data

    

users/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class SignupForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput, label='Confirm Password')


    def clean(self):
        cleaned_data = super(SignupForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("Passwords do not match. Please enter the same password in both fields.")

        return cleaned_data

users/templates/followers.html
{% extends 'based_layout.html' %}

{% load static %}

{% load custom_tags %}

{% block titulo %} Home {% endblock titulo %}

{% block title-page %} Profile Organizations  {% endblock title-page %}

{% block css %}
<link rel="stylesheet" href="{% static 'theme/css/volunteer.css' %}" type="text/css"/>
<link rel="stylesheet" href="{% static 'theme/lib/datatables/css/dataTables.bootstrap.min.css' %}" type="text/css"/>
{% endblock css %}

{% block content %}

<div class="be-content">

    <div class="page-head">
        <h2 class="page-head-title" id="profile" data-opcion="inicio"> Followers</h2>
    </div>

    <div class="main-content container-fluid ">
        <div class="row">
            <div class="col-md-7">
                <div class="user-display">
                    <div class="user-display-bg">
                        {% if user.background_image %}
                        <img src="{{ user.background_image.url }}" alt="Profile Background">
                        {% else %}
                        <img src="{% static 'media/bg2.jpg' %}">
                        {% endif %}
                    </div>
                    <div class="user-display-bottom">
                        <div class="user-display-avatar">
                            {% if user.profile_image %}
                            <img src="{{ user.profile_image.url }}" alt=" Avatar">
                            {% else %}
                            <img src="{% static 'media/avatar.png' %}">
                            {% endif %}

                        </div>
                        <div class="user-display-info">
                            <div class="name">
                                {% if user.first_name and user.last_name %}
                                {{ user.first_name }} {{ user.last_name }}
                                {% else %}
                                {{ user.username }}
                                {% endif %}
                            </div>
                            <div class="nick">
                                {% if user.headline %}
                                {{ user.headline }}
                                {% else %}
                                <p>Put your headline</p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="row user-display-details">
                            <div class="col-xs-4">
                                <a href="{% url 'users:following' user_id=user.id %}">
                                    <div class="title">Following</div>
                                </a>
                                     <div class="counter">{{ user.following.count }}</div>
                            </div>
                            <div class="col-xs-4">
                                <div class="title">Followers</div>
                                <div class="counter">{{ user.followers.count }}</div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <div class="row">
            <div class="col-md-7">
                <div class="user-display">
                    <div class="user-display-bottom">
                        <div class="row user-display-details">
                            <div class="title">{{ user.followers.count }} users are following you!!</div>
                            {% for relationship in relationships %}
                            <div class="post-header">
                                <a href="{% url 'users:profile' user_id=relationship.from_user.id %}">
                                    {% if relationship.from_user.profile_image %}
                                    <img src="{{ relationship.from_user.profile_image.url }}">
                                    {% else %}
                                    <img src="{% static 'media/avatar.png' %}">
                                    {% endif %}
                                    <span>
                                        {% if relationship.from_user.first_name and relationship.from_user.last_name %}
                                        {{ relationship.from_user.first_name }} {{ relationship.from_user.last_name}}
                                        {% else %}
                                        {{ relationship.from_user.username }}
                                        {% endif %}
                                        <div> {{ relationship.from_user.headline }} </div>
                                    </span>
                                </a>

                            </div>
                            {% endfor %}
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>


{% endblock content %}

{% block scripts %}

{% endblock scripts %}

users/templates/following.html
{% extends 'based_layout.html' %}

{% load static %}

{% load custom_tags %}

{% block titulo %} Home {% endblock titulo %}

{% block title-page %} Profile Organizations  {% endblock title-page %}

{% block css %}
<link rel="stylesheet" href="{% static 'theme/css/volunteer.css' %}" type="text/css"/>
<link rel="stylesheet" href="{% static 'theme/lib/datatables/css/dataTables.bootstrap.min.css' %}" type="text/css"/>
{% endblock css %}

{% block content %}

<div class="be-content">

    <div class="page-head">
        <h2 class="page-head-title" id="profile" data-opcion="inicio"> Following</h2>
    </div>

    <div class="main-content container-fluid ">
        <div class="row">
            <div class="col-md-7">
                <div class="user-display">
                    <div class="user-display-bg">
                        {% if user.background_image %}
                        <img src="{{ user.background_image.url }}" alt="Profile Background">
                        {% else %}
                        <img src="{% static 'media/bg2.jpg' %}">
                        {% endif %}
                    </div>
                    <div class="user-display-bottom">
                        <div class="user-display-avatar">
                            {% if user.profile_image %}
                            <img src="{{ user.profile_image.url }}" alt=" Avatar">
                            {% else %}
                            <img src="{% static 'media/avatar.png' %}">
                            {% endif %}

                        </div>
                        <div class="user-display-info">
                            <div class="name">
                                {% if user.first_name and user.last_name %}
                                {{ user.first_name }} {{ user.last_name }}
                                {% else %}
                                {{ user.username }}
                                {% endif %}
                            </div>
                            <div class="nick">
                                {% if user.headline %}
                                {{ user.headline }}
                                {% else %}
                                <p>Put your headline</p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="row user-display-details">
                            <div class="col-xs-4">
                                <div class="title">Following</div>
                                <div class="counter">{{ user.following.count }}</div>
                            </div>
                            <div class="col-xs-4">
                                <a href="{% url 'users:followers' user_id=user.id %}">
                                    <div class="title">Followers</div>
                                </a>
                                     <div class="counter">{{ user.followers.count }}</div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <div class="row">
            <div class="col-md-7">
                <div class="user-display">
                    <div class="user-display-bottom">
                        <div class="row user-display-details">
                            <div class="title">You are following {{ user.following.count }} users now !!</div>
                            {% for relationship in relationships %}
                            <div class="post-header">
                                <a href="{% url 'users:profile' user_id=relationship.to_user.id %}">
                                    {% if relationship.to_user.profile_image %}
                                    <img src="{{ relationship.to_user.profile_image.url }}">
                                    {% else %}
                                    <img src="{% static 'media/avatar.png' %}">
                                    {% endif %}
                                    <span>
                                        {% if relationship.to_user.first_name and relationship.to_user.last_name %}
                                        {{ relationship.to_user.first_name }} {{ relationship.to_user.last_name}}
                                        {% else %}
                                        {{ relationship.to_user.username }}
                                        {% endif %}
                                        <div> {{ relationship.to_user.headline }} </div>
                                    </span>

                                </a>
                                {% if user != relationship.to_user %}
                                <form action="{% url 'users:follow' user_id=relationship.to_user.id %}" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-primary">
                                        {% if relationship.to_user in user.following.all %}
                                        Unfollow
                                        {% else %}
                                        Follow
                                        {% endif %}
                                    </button>
                                </form>
                                {% endif %}
                            </div>
                            {% endfor %}
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>


{% endblock content %}

{% block scripts %}

{% endblock scripts %}

users/templates/sign-up.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <title>My Volunteer Site</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Volunteer Platform ">
    <meta name="author" content="Team 5">
    <title>{% block titulo %} Sing in {% endblock titulo %}</title>

    <!-- Material Desing Icons -->
    <link rel="stylesheet" href="{% static 'theme/lib/material-design-icons/css/material-design-iconic-font.min.css' %}" type="text/css" />

    <!-- Perfect Scrollbar -->
    <link rel="stylesheet" href="{% static 'theme/lib/perfect-scrollbar/css/perfect-scrollbar.min.css' %}" type="text/css" />

    <!-- Pace -->
    <script src="{% static 'libs/pace/1.0.0/pace.js' %} " type="text/javascript"></script>

    <!-- Select 2 -->
    <link rel="stylesheet" href="{% static 'libs/select2/4.0.3/dist/css/select2.min.css' %}"/>

    <!-- Main Theme CSS -->
    <link rel="stylesheet" href="{% static 'theme/css/style.css' %}" type="text/css"/>
    


</head>
<body class="be-splash-screen">
    {% for message in messages %}
        <div class="alert" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
    {% block content %}

    <div class="be-wrapper be-login">
        <div class="be-content">
            <div class="main-content container-fluid">
                <div class="splash-container">

                    <div class="panel panel-default panel-border-color nova-border-top-pantone">
                        <div class="panel-heading">
                            <img src="{% static 'media/logo.png' %}" alt="VolunteerConnect" width="320" height="120" class="logo-img">
                            <span class="splash-description"><strong>1.0</strong></span>
                        </div>
                        <div class="panel-body">
                            <form method="POST" action="">
                                {% csrf_token %}
                                <div class="form-group">
                                    <input id="username" type="text" name="username" placeholder="Username" autocomplete="off" class="form-control">
                                </div>
                                <div class="form-group">
                                    <input id="email" type="email" name="email" placeholder="Email" class="form-control">
                                </div>
                                <div class="form-group">
                                    <input id="password" type="password" name="password" placeholder="Password" class="form-control">
                                </div>
                                <div class="form-group">
                                    <input id="confirm_password" type="password" name="confirm_password" placeholder="Confirm Password" class="form-control">
                                </div>
                                <div class="form-group login-submit">
                                    <button data-dismiss="modal" type="submit" class="btn">Sign up</button>
                                </div>
                                <div class="splash-footer">
                                    <span> <a href="{% url 'users:login' %}">Login</a></span>
                                </div>
                            </form>
                        </div>
                    </div>

                    <!-- Include your additional signup content here -->

                </div>
            </div>
        </div>
    </div>
    {% endblock %}


    <!-- Include your JavaScript files here -->
        <!-- jQuery -->
        <script src="{% static 'theme/lib/jquery/jquery.min.js' %}" type="text/javascript"></script>

        <!-- Bootstrap-->
        <script src="{% static 'theme/lib/bootstrap/dist/js/bootstrap.min.js' %}" type="text/javascript"></script>
    
        <!-- Perfect Scrollbar -->
        <script src="{% static 'theme/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js' %}" type="text/javascript"></script>
    
        <!-- Pace -->
        <script src="{% static 'libs/pace/1.0.0/pace.js' %} " type="text/javascript"></script>
    
        <!-- Moment -->
        <script src="{% static 'libs/momentjs/2.18.1/moment.js' %}"></script>
    
        <!-- Pace -->
        <script src="{% static 'libs/pace/1.0.0/pace.js' %} " type="text/javascript"></script>
    
        <!-- Select 2 -->
        <script src="{% static 'libs/select2/4.0.3/dist/js/select2.min.js' %}"></script>
    
        <!-- Main Theme js -->
        <script src="{% static 'theme/js/main.js' %}"></script>
    
    
        <script type="text/javascript">
            $(document).ready(function(){
               //initialize the javascript
               App.init();
            });
        </script>

  </body>
</html>