apps/home/urls.py
from django.urls import path
from . import views
from .views import (search_api, user_feed)

app_name = 'home'

urlpatterns = [
     path('', user_feed, name='home'),
     path('search-api/', views.search_api, name='search_api'),
]

post/urls.py
from django.urls import path
from post.views import PostListCreate, CommentListCreate

urlpatterns = [
    path('postlist/', PostListCreate.as_view(), name='api_posts_list_create'),
    path('comment/', CommentListCreate.as_view(), name='api_comments_list_create'),

]

users/urls.py
from django.urls import path

from users.views import (
    user_login,
    user_logout,
    user_signup,
    forgot_password_view,
    profile,
    followers,
    following,
    follow, organization_memberships_view, follow1, BadgeListCreateView, SkillListCreateView,
    SkillRetrieveUpdateDestroyView, VolunteerListCreateView, VolunteerDetailView, VolunteerRetrieveUpdateDestroyView,
    AddSkillToVolunteerView, RemoveSkillFromVolunteerView, my_organizations_view, OrganizationListCreateView,
    OrganizationDetailView, OrganizationRetrieveUpdateDestroyView,
)

app_name = 'users'

urlpatterns = [
    # Users
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='user_logout'),
    path('badges/', BadgeListCreateView.as_view(), name='badge-list-create'),
    path('forgot-password/', forgot_password_view, name='forgot-password'),
    path('sign-up/', user_signup, name='sign-up'),
    path("profile/<int:user_id>/", profile, name="profile"),
    path("followers/<int:user_id>/", followers, name="followers"),
    path("following/<int:user_id>/", following, name="following"),
    path("follow/<int:user_id>", follow, name="follow"),
    path("follow1/<int:user_id>", follow1, name="follow1"),
    path('skills/', SkillListCreateView.as_view(), name='skill-list-create'),
    path('api/skills/<int:id>/', SkillRetrieveUpdateDestroyView.as_view(), name='skills-detail'),

    # Volunteers
    path('volunteers/', VolunteerListCreateView.as_view(), name='volunteer-list-create'),
    path('profile-volunteer/', VolunteerDetailView.as_view(), name='profile-volunteer'),
    path('volunteer/<int:pk>/', VolunteerDetailView.as_view(), name='volunteer-detail'),
    path('api/volunteer/<int:id>/', VolunteerRetrieveUpdateDestroyView.as_view(),
         name='volunteer-detail-update-delete'),
    path('api/volunteer/<int:id>/add_skill/', AddSkillToVolunteerView.as_view(), name='add-skill-to-volunteer'),
    path('api/volunteer/<int:id>/remove_skill/', RemoveSkillFromVolunteerView.as_view(),
         name='remove-skill-from-volunteer'),

    # Organizations
    path('my-organizations/', my_organizations_view, name='my-organizations'),
    path('organizations/', OrganizationListCreateView.as_view(), name='organizations-list-create'),
    path('organizations/<int:pk>/', OrganizationDetailView.as_view(), name='organization-detail'),
    path('api/organization/<int:id>/', OrganizationRetrieveUpdateDestroyView.as_view(), name='update-organization'),
    path('profile-organization/<int:org_id>/', OrganizationDetailView.as_view(), name='organization-detail'),
    path('organization-memberships/', organization_memberships_view, name='organization-memberships'),

]

volunteer_platform/urls.py
"""
URL configuration for volunteer_platform project.

"""
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', include('apps.home.urls')),
    path('admin/', admin.site.urls),
    path('', include(('apps.users.urls', 'users'), namespace='users')),
    path('post/', include('apps.post.urls')),
   # path('event/', include('apps.event.urls')),
    path('event/', include(('apps.event.urls', 'event'), namespace='event')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

apps/home/views.py
from django.shortcuts import render
from apps.post.models import Post 
from apps.event.models import Event
from django.http import JsonResponse
from django.db.models import Q
from apps.users.models import Volunteer, Organization
from django.utils import timezone
from django.db.models import Value, CharField
from django.contrib.auth.decorators import login_required


# Create your views here.

#def home(request):
 #   return render(request, 'home.html')

@login_required
def home(request):
    posts = Post.objects.all().order_by('-created_at').select_related('user')
    # Obtener los próximos eventos
    upcoming_events = Event.objects.filter(start_time__gt=timezone.now()).order_by('start_time')[:5]  # Ejemplo: los 5 próximos eventos

    context = {
        'posts': posts,
        'upcoming_events': upcoming_events,
        
    }

    return render(request, 'home.html', context)


@login_required
def user_feed(request):
    user_volunteer = Volunteer.objects.get(user=request.user)
    following_volunteers = user_volunteer.following_volunteers.all()
    following_users = [volunteer.user for volunteer in following_volunteers]
    following_users.append(request.user)

    posts = Post.objects.filter(user__in=following_users).order_by('-created_at')

    upcoming_events = Event.objects.filter(start_time__gt=timezone.now()).order_by('start_time')[:5]

    context = {
        'posts': posts,
        'upcoming_events': upcoming_events,

    }

    return render(request, 'home.html', context)


def search_api(request):
    query = request.GET.get('term', '')  # 'term' es el parámetro comúnmente usado por plugins de autocompletar

    # Búsqueda en el modelo 'Volunteer'
    volunteers = Volunteer.objects.filter(
        Q(user__first_name__icontains=query) | 
        Q(user__last_name__icontains=query) | 
        Q(bio__icontains=query) | 
        Q(phone_number__icontains=query) | 
        Q(headline__icontains=query)
    )

    # Búsqueda en el modelo 'Organization'
    organizations = Organization.objects.filter(
        Q(name__icontains=query) | 
        Q(description__icontains=query) | 
        Q(email__icontains=query) | 
        Q(phone_number__icontains=query)
    )

    results = {
    'volunteers': list(volunteers.values('id', 'user__first_name', 'user__last_name', 'bio').annotate(type=Value('volunteer', output_field=CharField()))),
    'organizations': list(organizations.values('id', 'name', 'description').annotate(type=Value('organization', output_field=CharField())))
     }
    return JsonResponse(results)

home/views.py
from django.shortcuts import render, redirect
from post.models import Post


# from apps.post.models import Post
# Create your views here.

# def home(request):
#    return render(request, 'home.html')

#
def home(request):
        if request.user.is_authenticated:
            posts = Post.objects.all().order_by('-created_at').select_related('user')
            return render(request, 'home.html', {'posts': posts})
        else:
            return redirect('users:login')

home/templates/based_layout.html
{% load static %}
{% load custom_tags %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}  {% endblock title %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Volunteer Platform ">
    <meta name="author" content="Team 5">

    <link rel="stylesheet" href="{% static 'theme/lib/material-design-icons/css/material-design-iconic-font.min.css' %}" type="text/css" />

    <link rel="stylesheet" href="{% static 'theme/lib/perfect-scrollbar/css/perfect-scrollbar.min.css' %}" type="text/css" />

    <link rel="stylesheet" href="{% static 'theme/lib/jqvmap/jqvmap.min.css' %}" type="text/css"/>

    <link rel="stylesheet" href="{% static 'theme/lib/jquery.vectormap/jquery-jvectormap-1.2.2.css' %}" type="text/css"/>

    <link rel="stylesheet" href="{% static 'theme/lib/datetimepicker/css/bootstrap-datetimepicker.min.css' %}" type="text/css"/>


    <!-- Awesome Icons -->
    <link rel="stylesheet" href="{% static 'libs/awesome-icons/4.7.0/css/font-awesome.min.css' %}" type="text/css">

    <!-- Pace -->
    <link rel="stylesheet" href="{% static 'libs/pace/1.0.0/pace.css' %}" type="text/css"/>

    <!-- Alertify -->
    <link rel="stylesheet" href="{% static 'libs/alertifyjs/1.10.0/css/alertify.min.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'libs/alertifyjs/1.10.0/css/themes/bootstrap.min.css' %}" type="text/css"/>

    <!-- Select 2 -->
    <link rel="stylesheet" href="{% static 'libs/select2/4.0.3/dist/css/select2.min.css' %}"/>

    <!-- Main Theme CSS -->
    <link rel="stylesheet" href="{% static 'theme/css/style.css' %}" type="text/css"/>
    {% block css %}
    {% endblock css %}
  </head>

<body>
    <div class="be-wrapper be-fixed-sidebar">
        <nav class="navbar navbar-default navbar-fixed-top be-top-header">
          <div class="container-fluid">
            <div class="navbar-header">
              <img src="{% static 'media/logo-vertical.png' %}" alt="VolunteerConnect" width="200" height="40" class="logo-img">
            </div>
            <div class="be-right-navbar be-right-navbar-flex">
              <div class="page-title"><span>My Volunteer Platform</span> </div>
              <div class="input-group input-group-sm">
                <input type="text" name="search" placeholder="Search..." class="form-control search-input"><span class="input-group-btn">
              </div>

              <ul class="nav navbar-nav navbar-right be-user-nav">
                <li class="dropdown">
                  <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle">
                      {% if request.user.profile_image %}
                      <img src="{{ request.user.profile_image.url }}" alt="">
                      {% else %}
                      <img src="{% static 'media/avatar.png' %}">
                      {% endif %}
                     <span class="user-name"> {{ request.user.username }}</span></a>

                  <ul role="menu" class="dropdown-menu">
                    <li>
                      <div class="user-info">
                        <div class="user-name">

                          {% if request.user.username == 'root' %}
                          <h4>Administrator</h4>
                          {% else %}

                              {% if request.user.first_name %}
                              <h5>{{ request.user.first_name }}</h5>
                              {% else %}
                              <h5> {{ request.user.username|upper }}</h5>
                              {% endif%}
                          {% endif %}
                            </div>
                      </div>
                    </li>
                    <li> <a href="{% url 'users:profile' user_id=user.id %}"><span class="icon mdi mdi-settings"></span> Profile</a></li>

                    <li><a href="{% url 'users:user_logout' %}"><span class="icon mdi mdi-power"></span> Logout</a></li>
                  </ul>
                </li>
              </ul>


              <ul class="nav navbar-nav navbar-right be-icons-nav">
                <li class="dropdown"><a href="#" role="button" aria-expanded="false" class="be-toggle-right-sidebar"><span class="icon mdi mdi-settings"></span></a></li>
                <li class="dropdown"><a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle"><span class="icon mdi mdi-notifications"></span><span class="indicator"></span></a>
                  <ul class="dropdown-menu be-notifications">
                    <li>
                      <div class="title">Notifications<span class="badge">3</span></div>
                      <div class="list">
                        <div class="be-scroller">
                          <div class="content">
                            <ul>
                              <li class="notification notification-unread"><a href="#">
                                  <div class="image"><img src="{% static 'theme/img/avatar2.png' %}" alt="Avatar"></div>
                                  <div class="notification-info">
                                    <div class="text"><span class="user-name">Jessica Caruso</span> accepted your invitation to join the team.</div><span class="date">2 min ago</span>
                                  </div></a></li>

                            </ul>
                          </div>
                        </div>
                      </div>
                      <div class="footer"> <a href="#">View all notifications</a></div>
                    </li>
                  </ul>
                </li>
                <li class="dropdown"><a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle"><span class="icon mdi mdi-apps"></span></a>
                  <ul class="dropdown-menu be-connections">
                    <li>
                      <div class="list">
                        <div class="content">
                          <div class="row">
                            <div class="col-xs-4"><a href="#" class="connection-item"><img src="{% static 'theme/img/github.png' %}" alt="Github"><span>GitHub</span></a></div>
                            </div>
                          <div class="row">
                            <div class="col-xs-4"><a href="#" class="connection-item"><img src="{% static 'theme/img/dribbble.png' %}" alt="Dribbble"><span>Dribbble</span></a></div>
                           </div>
                        </div>
                      </div>
                      <div class="footer"> <a href="#">More</a></div>
                    </li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </nav>

         <!-- Menu -->
        <div class="be-left-sidebar">
          <div class="left-sidebar-wrapper">
               <a href="#" class="left-sidebar-toggle nova-left-sidebar-toggle">{% block title-page %}  {% endblock title-page %}</a>
            <div class="left-sidebar-spacer">
              <div class="left-sidebar-scroll">
                <div class="left-sidebar-content">

                  {% tag_menu request.user%}

                </div>
              </div>
            </div>
          </div>
        </div>

        {% block content %}
        {% endblock content %}

      </div>


      <!-- jQuery -->
    <script src="{% static 'theme/lib/jquery/jquery.min.js' %}" type="text/javascript"></script>

    <!-- jQuery-Cookie -->
    <script src="{% static 'libs/jquery-cookie/1.4.1/jquery.cookie.js' %}"></script>

    <!-- Bootstrap-->
    <script src="{% static 'theme/lib/bootstrap/dist/js/bootstrap.min.js' %}" type="text/javascript"></script>

    <!-- Perfect Scrollbar -->
    <script src="{% static 'theme/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js' %}" type="text/javascript"></script>

    <!-- Pace -->
    <!-- <script data-pace-options='{ "startOnPageLoad": false }' src="{% static 'libs/pace/1.0.0/pace.min.js' %} " type="text/javascript"></script> -->

    <!-- Alertify -->
    <script src="{% static 'libs/alertifyjs/1.10.0/alertify.min.js' %}"></script>

    <!-- Moment -->
    <script src="{% static 'libs/momentjs/2.18.1/moment.js' %}"></script>

    <!-- Select 2 -->
    <script src="{% static 'libs/select2/4.0.3/dist/js/select2.min.js' %}"></script>

    <!-- Main Theme js -->
    <script src="{% static 'theme/js/main.js' %}"></script>

    <script type="text/javascript">

      $(document).ready(function(){
          //initialize the javascript
          App.init();
      });

  </script>

{% block scripts %}

{% endblock scripts %}

    </body>
</html>

home/templates/home.html
{% extends 'based_layout.html' %}

{% load static %}
{% load custom_tags %}

{% block titulo %} Home {% endblock titulo %}
{% block title-page %} Profile Organizations  {% endblock title-page %}
{% block css %}
    <link rel="stylesheet" href="{% static 'theme/css/volunteer.css' %}" type="text/css"/>

{% endblock css %}

{% block content %}
<div class="be-content">
    <div class="page-head">
        <h2 class="page-head-title" id="profile" data-opcion="inicio">User Feed</h2>
    </div>

    <div class="main-content container-fluid ">
        <div class="row">
            <div class="col-md-9">
                <!-- Botón para activar el modal de crear post -->
                <button type="button" class="btn btn-primary mb-3" data-toggle="modal" data-target="#createPostModal">
                    Create Post
                </button>

                <!-- Modal de Crear Post -->
                <div class="modal fade" id="createPostModal" tabindex="-1" role="dialog"
                     aria-labelledby="createPostModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="createPostModalLabel">Create Post</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form id="postForm" method="POST" action="#">
                                    {% csrf_token %}
                                    <!-- Title Input Field -->
                                    <div class="form-group">
                                        <label for="postTitle">Title:</label>
                                        <input type="text" class="form-control" id="postTitle" name="title">
                                    </div>

                                    <!-- Content Textarea -->
                                    <div class="form-group">
                                        <label for="postContent">Content:</label>
                                        <textarea class="form-control" id="postContent" name="content"
                                                  rows="6"></textarea>
                                    </div>

                                    <!-- File Input Field -->
                                    <div class="form-group">
                                        <label for="postFile">File:</label>
                                        <input type="file" class="form-control-file" id="postFile"
                                               name="{{ form.file.name }}">
                                    </div>

                                    <!-- Submit button -->
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                {% for post in posts %}
                <article id="post-{{ post.id }}" class="post">
                <div class="user-info-list panel panel-default panel-border">
                    <header class="post-header">
                        <a href="{% url 'users:profile' user_id=post.user.id %}">
                            {% if post.user.profile_image %}
                                <img src="{{ post.user.profile_image.url }}" alt="">
                            {% else %}
                                 <img src="{% static 'media/avatar.png' %}">
                            {% endif %}
                            <span>
                                {% if post.user.first_name and post.user.last_name %}
                                {{ post.user.first_name }} {{ post.user.last_name }}
                                {% else %}
                                {{ post.user.username }}
                                {% endif %}
                                <div> {{ post.user.headline }} </div>
                                <div> time </div>
                            </span>

                            <!---<span>{{ post.created_at|date:"F d, h:i A" }}</span>  --->
                        </a>
                    </header>

                    <div class="panel-body">
                        <section class="post-contenido">
                            {{ post.content }}
                        </section>
                        {% if post.file %}
                        <!-- Check if a file is attached to the post -->
                        <img src="{{ post.file.url }}" class="img-fluid mb-3" style="max-width: 600px; height: 600;"
                             alt="Post Image">
                        {% endif %}

                        <!-- Comments -->
                        <h3 class="mt-3">Comments:</h3>
                        {% if post.comments.all %}
                        <ul class="list-group">
                            {% for comment in post.comments.all %}
                            <li class="list-group-item">
                                <strong>{{ comment.user.username }}</strong> said: {{ comment.text }}
                                <span class="text-muted"> ({{ comment.created_at | date:"F d, Y h:i A" }})</span>
                            </li>
                            {% empty %}
                            <li class="list-group-item">No comments yet.</li>
                            {% endfor %}
                        </ul>
                        {% else %}
                        <p class="text-muted">No comments yet.</p>
                        {% endif %}

                        <!-- Form to add comments -->
                        <button type="button" class="btn btn-secondary mt-3 add-comment-btn"
                                data-post-id="{{ post.id }}">Add Comment
                        </button>
                        <form class="commentForm hidden" method="post" data-post-id="{{ post.id }}">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="{{ form.text.id_for_label }}">Add a comment:</label>
                                <textarea class="form-control" id="{{ form.text }}" name="text" rows="6"></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary mt-3">Submit</button>
                        </form>
                    </div>
                </div>
                </article>
                {% empty %}
                <p class="mt-4">No posts available.</p>
                {% endfor %}
            </div>
            <div class="col-md-3 nova-sidebar">
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-border panel-contrast user-info-list nova-panel-default">
                            <div class="panel-heading panel-heading-default nova-panel-heading-formulario">
                                Events
                            </div>
                            <div class="panel-body">
                                <table class="no-border no-strip skills">
                                    <tbody class="no-border-x no-border-y">
                                    <tr>
                                        <td class="">
                                            <div class="col-md-12">
                                                <i class="fa fa-calendar" aria-hidden="true"></i> Event: date: Title
                                                Event
                                            </div>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Script para enviar el formulario por AJAX -->
<script>
 document.addEventListener('DOMContentLoaded', (event) => {

const postForm = document.getElementById('postForm');

if (postForm) {
    postForm.addEventListener('submit', function(event) {
        event.preventDefault();

        const titleElement = document.getElementById('postTitle');
        const contentElement = document.getElementById('postContent');
        const fileElement = document.getElementById('postFile');

        if (!titleElement || !contentElement) {
            console.error("Error: No se encontraron los elementos del formulario.");
            return;
        }

        const title = titleElement.value.trim();
        const content = contentElement.value.trim();

        if (!title || !content) {
            alert('Ambos campos, título y contenido, son obligatorios.');
            return;
        }

        const formData = new FormData(postForm);

        // Verificar si se ha seleccionado un archivo y agregarlo al formData
        if (fileElement.files.length > 0) {
            formData.append('file', fileElement.files[0]);
        }

        const headers = new Headers();
        headers.append('X-CSRFToken', getCookie('csrftoken'));

        fetch("/post/postlist/", {
            method: "POST",
            headers: headers,
            body: formData
        })
        .then(response => {
            if (!response.ok) {
                return response.text().then(errorText => {
                    throw new Error(errorText || 'La respuesta de la red no fue correcta');
                });
            }
            return response.json();
        })
        .then(data => {
            if (data.id) {
                alert("¡Publicación creada con éxito!");
                location.reload();  // Recargar la página
            } else {
                alert("Error: " + JSON.stringify(data));
            }
        })
        .catch(error => {
            console.error("Error:", error);
            alert("Ocurrió un error: " + error.message);
        });
    });
}

function getCookie(name) {
    const value = "; " + document.cookie;
    const parts = value.split("; " + name + "=");
    if (parts.length == 2) return parts.pop().split(";").shift();
}

  // Function to get CSRF token
  function getCSRFToken() {
      const name = "csrftoken=";
      const decodedCookie = decodeURIComponent(document.cookie);
      const cookieArray = decodedCookie.split(';');

      for (let i = 0; i < cookieArray.length; i++) {
          let cookie = cookieArray[i];
          while (cookie.charAt(0) === ' ') {
              cookie = cookie.substring(1);
          }
          if (cookie.indexOf(name) === 0) {
              return cookie.substring(name.length, cookie.length);
          }
      }
      return "";
  }


  let commentForms = document.querySelectorAll('.commentForm');
      commentForms.forEach(form => {
      form.addEventListener("submit", function(event) {
          event.preventDefault();

          let textArea = this.querySelector('textarea[name="text"]');
          if (!textArea.value.trim()) {
              alert('The comment field is required.');
              return;
          }

          let postId = this.getAttribute('data-post-id');
          let formData = new FormData();
          formData.append('csrfmiddlewaretoken', getCSRFToken());
          formData.append('text', textArea.value);
          formData.append('post', postId);

          let headers = new Headers();
          headers.append('X-CSRFToken', getCookie('csrftoken'));

          fetch("/post/comment/", {
              method: "POST",
              headers: headers,
              body: formData
          })
          .then(response => {
              if (!response.ok) {
                  return response.text().then(errorText => {
                      console.log("Error details:", errorText);
                      throw new Error('Network response was not ok');
                  });
              }
              return response.json();
          })
          .then(data => {
              if (data.id) {
                  alert("Comment added successfully!");
                  location.reload();
              } else {
                  alert("Error: " + JSON.stringify(data));
              }
          })
          .catch(error => {
              console.error("Error:", error);
              alert("An error occurred. Please try again.");
          });
      });
  });


    // Event listeners for each comment button
    let commentButtons = document.querySelectorAll('.add-comment-btn');
    commentButtons.forEach(btn => {
        btn.addEventListener("click", function() {
            let postId = this.getAttribute('data-post-id');
            let form = document.querySelector(`.commentForm[data-post-id="${postId}"]`);
            form.classList.toggle('hidden'); // Mostrar/Ocultar el formulario al hacer click
        });
    });

});

</script>
{% endblock content %}

{% block scripts %}
{% endblock scripts %}

home/templates/menu.html
{% load custom_tags %}

<ul class="sidebar-elements nova-sidebar-elements">
    <li class="divider">Menu</li>
    <li id="home">
        <a href="{% url 'home:home' %}">
            <i class="icon mdi mdi-home"></i>
            <span>Home</span>
        </a>
    </li>

        <li class="parent"><a href="#"><i class="icon mdi mdi-money"></i><span>Organizations</span></a>
            <ul class="sub-menu">
                    <li id="My organizations">
                        <a href="{% url 'users:my-organizations' %}">
                            <span>My organizations</span>
                        </a>
                    </li>

                    <li id="Memberships">
                        <a href="{% url 'users:organization-memberships' %}">
                            <span>Memberships</span>
                        </a>
                    </li>

                    <li id="Event Managment">
                        <a href="">
                            <span>Events</span>
                        </a>
                    </li>

                    <li id="Recruitment Managment">
                        <a href="">
                            <span>Recruitment Managment</span>
                        </a>
                    </li>


              </ul>
        </li>
        <li class="parent"><a href="#"><i class="icon mdi mdi-money"></i><span>Connection</span></a>
            <ul class="sub-menu">
                    <li id="Followers">
                        <a href="{% url 'users:followers' user_id=user.id %}">
                            <span>Followers</span>
                        </a>
                    </li>

                    <li id="Following">
                        <a href="{% url 'users:following' user_id=user.id %}">
                            <span>Following</span>
                        </a>
                    </li>
            </ul>
        </li>


</ul>