apps/home/urls.py
from django.urls import path
from . import views
from .views import (search_api, user_feed)

app_name = 'home'

urlpatterns = [
     path('', user_feed, name='home'),
     path('search-api/', views.search_api, name='search_api'),
]

apps/users/urls.py
from django.urls import path
from .views import (user_logout,user_login,forgot_password_view,profile_organizations_view, 
                    SkillRetrieveUpdateDestroyView, VolunteerRetrieveUpdateDestroyView, 
                    BadgeListCreateView, SkillListCreateView, VolunteerListCreateView, 
                    OrganizationListCreateView,VolunteerDetailView, AddSkillToVolunteerView,
    RemoveSkillFromVolunteerView, my_organizations_view ,OrganizationDetailView,
    OrganizationRetrieveUpdateDestroyView, organization_memberships_view,user_signup, update_profile_picture,
    update_background_image,update_profile_logo,update_obackground_image,AddInterestToVolunteerView, 
    RemoveInterestFromVolunteerView, AddInterestToOrganizationView, RemoveInterestFromOrganizationView,
    VolunteerMatchView,VolunteerRelationships,unfollow_volunteer,follow_volunteer,follow_organization,unfollow_organization,
    skills_admin_view, AddSkillView, AddInterestView, interest_admin_view,AddOrganizationMembershipView,accept_membership_view,
    SuggestedVolunteerList, like_post, is_liked, VolunteerDetailView2,
)
app_name = 'users'

urlpatterns = [
    #Users
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='user_logout'),
    path('badges/', BadgeListCreateView.as_view(), name='badge-list-create'),
    path('forgot-password/', forgot_password_view, name='forgot-password'),
    path('sign-up/', user_signup, name='sign-up'),

    path('skills/', SkillListCreateView.as_view(), name='skill-list-create'),
    path('api/skills/<int:id>/', SkillRetrieveUpdateDestroyView.as_view(), name='skills-detail'),

    #Volunteers
    path('volunteers/', VolunteerListCreateView.as_view(), name='volunteer-list-create'),
    path('profile-volunteer/', VolunteerDetailView.as_view(), name='profile-volunteer'),
    path('volunteer/<int:pk>/', VolunteerDetailView.as_view(), name='volunteer-detail'),  
    path('api/volunteer/<int:id>/add_skill/', AddSkillToVolunteerView.as_view(), name='add-skill-to-volunteer'),
    path('api/volunteer/<int:id>/remove_skill/', RemoveSkillFromVolunteerView.as_view(), name='remove-skill-from-volunteer'),
    path('api/volunteer/<int:id>/update_profile_picture/', update_profile_picture, name='update-profile-picture'),
    path('api/volunteer/<int:id>/update_background_image/', update_background_image, name='update-background-image'),
    path('api/volunteer/<int:id>/add_interest/', AddInterestToVolunteerView.as_view(), name='add-intereest-to-volunteer'),
    path('api/volunteer/<int:id>/remove_interest/', RemoveInterestFromVolunteerView.as_view(), name='remove-interest-from-volunteer'),
    path("relationships/", VolunteerRelationships, name="relationships"),
    path('unfollow_volunteer/<int:volunteer_id>/', unfollow_volunteer, name='unfollow-volunteer'),
    path('follow_volunteer/<int:volunteer_id>/', follow_volunteer, name='follow-volunteer'),
    path('api/suggestions/', SuggestedVolunteerList.as_view(), name='suggested_volunteers'),
    path('like_post/<int:post_id>/', like_post, name='like_post'),
    path('is_liked/<int:post_id>/', is_liked, name='is_liked'),

    #Organizations
    path('my-organizations/', my_organizations_view, name='my-organizations'),
    path('organizations/', OrganizationListCreateView.as_view(), name='organizations-list-create'),
    path('organizations/<int:pk>/', OrganizationDetailView.as_view(), name='organization-detail'),
    path('api/organization/<int:id>/', OrganizationRetrieveUpdateDestroyView.as_view(), name='update-organization'),
    path('api/organization/<int:id>/update_profile_logo/', update_profile_logo, name='update-profile-logo'),
    path('api/organization/<int:id>/update_background_image/', update_obackground_image, name='update-obackground-image'),
    path('api/organization/<int:id>/add_interest/', AddInterestToOrganizationView.as_view(), name='add-intereest-to-organization'),
    path('api/organization/<int:id>/remove_interest/', RemoveInterestFromOrganizationView.as_view(), name='remove-interest-from-organization'),
    path('organization-match/', VolunteerMatchView.as_view(), name='organization-match'),
    path('organization-match/subscribe/<int:organization_id>/', VolunteerMatchView.as_view(), name='organization-subscribe'),

    path('unfollow_organization/<int:organization_id>/', unfollow_organization, name='unfollow-organization'),
    path('organization/<int:organization_id>/follow', follow_organization, name='follow-organization'),
    


    path('profile-organization/<int:pk>/', OrganizationDetailView.as_view(), name='profile-organization'),
    path('organization-memberships/', organization_memberships_view, name='organization-memberships'),
     path('accept-membership/<int:membership_id>/', accept_membership_view, name='accept-membership'),

    #Administration
    path('skills-admin/', skills_admin_view, name='skills-admin'),
    path('add-skill/', AddSkillView.as_view(), name='add-skill'),

    path('interest-admin/', interest_admin_view, name='interest-admin'),
    path('add-interest/', AddInterestView.as_view(), name='add-interest'),


]

event/urls.py
from django.urls import path 

from .views import EventViewSet, RegistrationEventsViewSet, ProgramViewSet,events_management_view

app_name = 'event'

urlpatterns = [
   path('events/', EventViewSet.as_view(), name='api_createevent'),
   path('registration-events/', RegistrationEventsViewSet.as_view(), name='api_registrationevent'),
   path('programs/', ProgramViewSet.as_view(), name='api_programs'),

    path('events-management/', events_management_view, name='events-management'),

]

post/urls.py
from django.urls import path
from post.views import PostListCreate, CommentListCreate

urlpatterns = [
    path('postlist/', PostListCreate.as_view(), name='api_posts_list_create'),
    path('comment/', CommentListCreate.as_view(), name='api_comments_list_create'),

]

users/urls.py
from django.urls import path

from users.views import (
    user_login,
    user_logout,
    user_signup,
    forgot_password_view,
    profile,
    followers,
    following,
    follow, organization_memberships_view, follow1, BadgeListCreateView, SkillListCreateView,
    SkillRetrieveUpdateDestroyView, VolunteerListCreateView, VolunteerDetailView, VolunteerRetrieveUpdateDestroyView,
    AddSkillToVolunteerView, RemoveSkillFromVolunteerView, my_organizations_view, OrganizationListCreateView,
    OrganizationDetailView, OrganizationRetrieveUpdateDestroyView,
)

app_name = 'users'

urlpatterns = [
    # Users
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='user_logout'),
    path('badges/', BadgeListCreateView.as_view(), name='badge-list-create'),
    path('forgot-password/', forgot_password_view, name='forgot-password'),
    path('sign-up/', user_signup, name='sign-up'),
    path("profile/<int:user_id>/", profile, name="profile"),
    path("followers/<int:user_id>/", followers, name="followers"),
    path("following/<int:user_id>/", following, name="following"),
    path("follow/<int:user_id>", follow, name="follow"),
    path("follow1/<int:user_id>", follow1, name="follow1"),
    path('skills/', SkillListCreateView.as_view(), name='skill-list-create'),
    path('api/skills/<int:id>/', SkillRetrieveUpdateDestroyView.as_view(), name='skills-detail'),

    # Volunteers
    path('volunteers/', VolunteerListCreateView.as_view(), name='volunteer-list-create'),
    path('profile-volunteer/', VolunteerDetailView.as_view(), name='profile-volunteer'),
    path('volunteer/<int:pk>/', VolunteerDetailView.as_view(), name='volunteer-detail'),
    path('api/volunteer/<int:id>/', VolunteerRetrieveUpdateDestroyView.as_view(),
         name='volunteer-detail-update-delete'),
    path('api/volunteer/<int:id>/add_skill/', AddSkillToVolunteerView.as_view(), name='add-skill-to-volunteer'),
    path('api/volunteer/<int:id>/remove_skill/', RemoveSkillFromVolunteerView.as_view(),
         name='remove-skill-from-volunteer'),

    # Organizations
    path('my-organizations/', my_organizations_view, name='my-organizations'),
    path('organizations/', OrganizationListCreateView.as_view(), name='organizations-list-create'),
    path('organizations/<int:pk>/', OrganizationDetailView.as_view(), name='organization-detail'),
    path('api/organization/<int:id>/', OrganizationRetrieveUpdateDestroyView.as_view(), name='update-organization'),
    path('profile-organization/<int:org_id>/', OrganizationDetailView.as_view(), name='organization-detail'),
    path('organization-memberships/', organization_memberships_view, name='organization-memberships'),

]

volunteer_platform/urls.py
"""
URL configuration for volunteer_platform project.

"""
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', include('apps.home.urls')),
    path('admin/', admin.site.urls),
    path('', include(('apps.users.urls', 'users'), namespace='users')),
    path('post/', include('apps.post.urls')),
   # path('event/', include('apps.event.urls')),
    path('event/', include(('apps.event.urls', 'event'), namespace='event')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

apps/home/views.py
from django.shortcuts import render
from apps.post.models import Post 
from apps.event.models import Event
from django.http import JsonResponse
from django.db.models import Q
from apps.users.models import Volunteer, Organization
from django.utils import timezone
from django.db.models import Value, CharField
from django.contrib.auth.decorators import login_required


# Create your views here.

#def home(request):
 #   return render(request, 'home.html')

@login_required
def home(request):
    posts = Post.objects.all().order_by('-created_at').select_related('user')
    # Obtener los próximos eventos
    upcoming_events = Event.objects.filter(start_time__gt=timezone.now()).order_by('start_time')[:5]  # Ejemplo: los 5 próximos eventos

    context = {
        'posts': posts,
        'upcoming_events': upcoming_events,
        
    }

    return render(request, 'home.html', context)


@login_required
def user_feed(request):
    user_volunteer = Volunteer.objects.get(user=request.user)
    following_volunteers = user_volunteer.following_volunteers.all()
    following_users = [volunteer.user for volunteer in following_volunteers]
    following_users.append(request.user)

    posts = Post.objects.filter(user__in=following_users).order_by('-created_at')

    upcoming_events = Event.objects.filter(start_time__gt=timezone.now()).order_by('start_time')[:5]

    context = {
        'posts': posts,
        'upcoming_events': upcoming_events,

    }

    return render(request, 'home.html', context)


def search_api(request):
    query = request.GET.get('term', '')  # 'term' es el parámetro comúnmente usado por plugins de autocompletar

    # Búsqueda en el modelo 'Volunteer'
    volunteers = Volunteer.objects.filter(
        Q(user__first_name__icontains=query) | 
        Q(user__last_name__icontains=query) | 
        Q(bio__icontains=query) | 
        Q(phone_number__icontains=query) | 
        Q(headline__icontains=query)
    )

    # Búsqueda en el modelo 'Organization'
    organizations = Organization.objects.filter(
        Q(name__icontains=query) | 
        Q(description__icontains=query) | 
        Q(email__icontains=query) | 
        Q(phone_number__icontains=query)
    )

    results = {
    'volunteers': list(volunteers.values('id', 'user__first_name', 'user__last_name', 'bio').annotate(type=Value('volunteer', output_field=CharField()))),
    'organizations': list(organizations.values('id', 'name', 'description').annotate(type=Value('organization', output_field=CharField())))
     }
    return JsonResponse(results)

home/views.py
from django.shortcuts import render, redirect
from post.models import Post


# from apps.post.models import Post
# Create your views here.

# def home(request):
#    return render(request, 'home.html')

#
def home(request):
        if request.user.is_authenticated:
            posts = Post.objects.all().order_by('-created_at').select_related('user')
            return render(request, 'home.html', {'posts': posts})
        else:
            return redirect('users:login')

apps/home/templates/based_layout.html
{% load static %}
{% load custom_tags %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}  {% endblock title %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Volunteer Platform ">
    <meta name="author" content="Team 5">
   
    <link rel="stylesheet" href="{% static 'theme/lib/material-design-icons/css/material-design-iconic-font.min.css' %}" type="text/css" />
    
    <link rel="stylesheet" href="{% static 'theme/lib/perfect-scrollbar/css/perfect-scrollbar.min.css' %}" type="text/css" />

    <link rel="stylesheet" href="{% static 'theme/lib/jqvmap/jqvmap.min.css' %}" type="text/css"/>

    <link rel="stylesheet" href="{% static 'theme/lib/jquery.vectormap/jquery-jvectormap-1.2.2.css' %}" type="text/css"/>

    <link rel="stylesheet" href="{% static 'theme/lib/datetimepicker/css/bootstrap-datetimepicker.min.css' %}" type="text/css"/>


    <!-- Awesome Icons -->
    <link rel="stylesheet" href="{% static 'libs/awesome-icons/4.7.0/css/font-awesome.min.css' %}" type="text/css">

    <!-- Pace -->
    <link rel="stylesheet" href="{% static 'libs/pace/1.0.0/pace.css' %}" type="text/css"/>

    <!-- Alertify -->
    <link rel="stylesheet" href="{% static 'libs/alertifyjs/1.10.0/css/alertify.min.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'libs/alertifyjs/1.10.0/css/themes/bootstrap.min.css' %}" type="text/css"/>

    <!-- Select 2 -->
    <link rel="stylesheet" href="{% static 'libs/select2/4.0.3/dist/css/select2.min.css' %}"/>

    <!-- Main Theme CSS -->
    <link rel="stylesheet" href="{% static 'theme/css/style.css' %}" type="text/css"/>
    {% block css %}
    {% endblock css %} 
  </head>
   
<body>
    <div class="be-wrapper be-fixed-sidebar">
        <nav class="navbar navbar-default navbar-fixed-top be-top-header">
          <div class="container-fluid">
            <div class="navbar-header">
              <img src="{% static 'media/logo-vertical.png' %}" alt="VolunteerConnect" width="200" height="40" class="logo-img">
            </div>
            <div class="be-right-navbar be-right-navbar-flex">
              <div class="page-title"><span>My Volunteer Platform</span> </div>
              
              <div class="input-group input-search input-group-sm">

                <input type="text" name="search" placeholder="Search..." class="form-control search-input">
                <span class="input-group-btn">
                  <button type="button" class="btn btn-default"><i class="icon mdi mdi-search"></i></button></span>
  
                <div id="search-results"></div>  <!-- Div donde se mostrarán los resultados -->
              </div>
              
              <ul class="nav navbar-nav navbar-right be-user-nav">
                <li class="dropdown">
                  <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle">
                    {% if request.user.volunteer.profile_picture %}
                     <img src="{{ request.user.volunteer.profile_picture.url }}" alt="{{ request.user.get_full_name }}">
                    {% else %}
                     <img src="{% static 'theme/img/avatar.png' %}" alt="Default Avatar">
                {% endif %}
                <span class="user-name"> {{ request.user.username }}</span></a>

                  <ul role="menu" class="dropdown-menu">
                    <li>
                      <div class="user-info">
                        <div class="user-name">
                          
                          {% if request.user.username == 'root' %}
                          <h4>Administrator</h4>
                          {% else %}

                              {% if request.user.first_name %}
                              <h5>{{ request.user.first_name }}</h5>
                              {% else %}
                              <h5> {{ request.user.username|upper }}</h5>
                              {% endif%}
                          {% endif %}
                            </div>
                      </div>
                    </li>
                    {% get_volunteer_id as volunteer_id %}
                    <li> 
                      {% if volunteer_id %}
                      <a href="{% url 'users:volunteer-detail' volunteer_id %}"><span class="icon mdi mdi-face"></span></span>Profile</a>   {% else %}
                      <a href="" ><span class="icon mdi mdi-face"></span>Profile</a> <!-- Enlace con href vacío -->
                       {% endif %}
                        </a>
                    
                    </li>
                    <li> <a href="{% url 'users:organization-match' %}"><span class="icon mdi mdi-search"></span> Matching Interests </a></li>
                    <li>
                      <a href="{% url 'users:relationships'%}">
                          <span class="icon mdi mdi-accounts-list-alt"></span> Relationships 
                      </a>
                  </li>
                    <li><a href="{% url 'users:user_logout' %}"><span class="icon mdi mdi-power"></span> Logout</a></li>
                  </ul>
                </li>
              </ul>
            
              <ul class="nav navbar-nav navbar-right be-icons-nav">
                <li class="dropdown"><span></span></li>
                <li class="dropdown"><a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle"><span class="icon mdi mdi-notifications"></span><span class="indicator"></span></a>
                  <ul class="dropdown-menu be-notifications">
                    <li>
                      <div class="title">Notifications<span class="badge">3</span></div>
                      <div class="list">
                        <div class="be-scroller">
                          <div class="content">
                            <ul>
                              <li class="notification notification-unread"><a href="#">
                                  <div class="image"><img src="{% static 'theme/img/avatar2.png' %}" alt="Avatar"></div>
                                  <div class="notification-info">
                                    <div class="text"><span class="user-name">Jessica Caruso</span> accepted your invitation to join the team.</div><span class="date">2 min ago</span>
                                  </div></a>
                               </li>
                            </ul>
                          </div>
                        </div>
                      </div>
                      <div class="footer"> <a href="#">View all notifications</a></div>
                    </li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </nav>

         <!-- Menu -->
        <div class="be-left-sidebar">
          <div class="left-sidebar-wrapper">
               <a href="#" class="left-sidebar-toggle nova-left-sidebar-toggle">{% block title-page %}  {% endblock title-page %}</a>
            <div class="left-sidebar-spacer">
              <div class="left-sidebar-scroll">
                <div class="left-sidebar-content">
                
                  {% tag_menu request.user%}
                
                </div>
              </div>
            </div>
          </div>
        </div>

        {% block content %}
        {% endblock content %}
      
      </div>
    

      <!-- jQuery -->
    <script src="{% static 'theme/lib/jquery/jquery.min.js' %}" type="text/javascript"></script>

    <!-- jQuery-Cookie -->
    <script src="{% static 'libs/jquery-cookie/1.4.1/jquery.cookie.js' %}"></script>

    <!-- Bootstrap-->
    <script src="{% static 'theme/lib/bootstrap/dist/js/bootstrap.min.js' %}" type="text/javascript"></script>

    <!-- Perfect Scrollbar -->
    <script src="{% static 'theme/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js' %}" type="text/javascript"></script>

    <!-- Pace -->
    <!-- <script data-pace-options='{ "startOnPageLoad": false }' src="{% static 'libs/pace/1.0.0/pace.min.js' %} " type="text/javascript"></script> -->

    <!-- Alertify -->
    <script src="{% static 'libs/alertifyjs/1.10.0/alertify.min.js' %}"></script>

    <!-- Moment -->
    <script src="{% static 'libs/momentjs/2.18.1/moment.js' %}"></script>

    <!-- Select 2 -->
    <script src="{% static 'libs/select2/4.0.3/dist/js/select2.min.js' %}"></script>

    <!-- Main Theme js -->
    <script src="{% static 'theme/js/main.js' %}"></script>

    <script type="text/javascript">
      $(document).ready(function(){
          //initialize the javascript
          App.init();
      });
    
      document.addEventListener('DOMContentLoaded', function() {
          const searchInput = document.querySelector('.search-input');
          const resultsContainer = document.getElementById('search-results');
    
          searchInput.addEventListener('input', function() {
              const searchTerm = searchInput.value;
    
              if (searchTerm.length < 2) {  // Puedes ajustar el número mínimo de caracteres aquí
                  resultsContainer.innerHTML = '';
                  return;
              }
    
              fetch(`{% url 'home:search_api' %}?term=${encodeURIComponent(searchTerm)}`)
              .then(response => response.json())
              .then(data => {
                  let html = '<ul>';
                  // Iterar sobre volunteers
                  data.volunteers.forEach(item => {
                      html += `<li><a href="/volunteer/${item.id}/">${item.user__first_name} ${item.user__last_name}</a></li>`;
                  });
                  // Iterar sobre organizations
                  data.organizations.forEach(item => {
                      html += `<li><a href="/organizations/${item.id}/">${item.name}</a> </li>`;
                  });
                  html += '</ul>';
                  resultsContainer.innerHTML = html;
              })
              .catch(error => {
                  console.error('Error:', error);
                  resultsContainer.innerHTML = '<p>Error loading results.</p>';
              });
          });
      });
    </script>

{% block scripts %}

{% endblock scripts %}

    </body> 
</html>

apps/home/templates/menu.html
{% load custom_tags %}

<ul class="sidebar-elements nova-sidebar-elements">
    <li class="divider">Menu</li>
    <li id="home">
        <a href="{% url 'home:home' %}">
            <i class="icon mdi mdi-home"></i>
            <span>Home</span>
        </a>
    </li>
        <li class="parent"><a href="#"><i class="icon mdi mdi-city-alt"></i><span>Organizations</span></a>
            <ul class="sub-menu">
                    <li id="My organizations">
                        <a href="{% url 'users:my-organizations' %}">
                            <span>My organizations</span>
                        </a>
                    </li>

                    <li id="Memberships">
                        <a href="{% url 'users:organization-memberships' %}">
                            <span>Memberships</span>
                        </a>
                    </li>

                    <li id="Event Managment">
                        <a href="{% url 'event:events-management' %}">
                            <span>Events</span>
                        </a>
                    </li>
                
                    <li id="Recruitment Managment">
                        <a href="">
                            <span>Recruitment </span>
                        </a>
                    </li>
                

              </ul>
        </li>

        <li class="parent"><a href="#"><i class="icon mdi mdi-settings"></i><span>Administration</span></a>
            <ul class="sub-menu">
                    <li id="Skills">
                        <a href="{% url 'users:skills-admin' %}">
                            <span>Skills</span>
                        </a>
                    </li>

                    <li id="Skills">
                        <a href="{% url 'users:interest-admin' %}">
                            <span>Interest</span>
                        </a>
                    </li>
              </ul>
        </li>
  
</ul>